#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pollmydevice[-1]
	add ucitrack pollmydevice
	set ucitrack.@pollmydevice[-1].init=pollmydevice
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
