#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

DIR=/sbin
PROG=pollmydevice

error(){
	echo "${initscript}:" "$@" 1>&2
}

xappend() {
	local filename="$1"
	local value="$2"
	echo "${value#--}" >> "$filename"
}

section_enabled(){
	config_get_bool enabled "$1" 'enabled' 0
	[ $enabled -gt 0 ]
}

start_service_daemon(){
	local s="$1"

	section_enabled "$s" || return 1

	uci set pollmydevice.rs485.mode='disabled'

	uci set pollmydevice.rs232.mode='disabled'

	uci set pollmydevice.tcp_server.port='NONE'

	uci set pollmydevice.tcp_client.host='hub.m2m24.ru'
	uci set pollmydevice.tcp_client.port='6008'

	uci commit pollmydevice
	
	procd_open_instance
	procd_set_param command "$DIR/$PROG"
	procd_set_param respawn
	procd_close_instance
}

start_service(){
	config_load 'pollmydevice'
	config_foreach start_service_daemon 'pollmydevice'
}

service_triggers()
{
        procd_add_reload_trigger "pollmydevice"
}

stop(){
	service_stop $DIR/$PROG
}

reload_service() {
	service_stop $DIR/$PROG
	config_load 'pollmydevice'
	config_foreach start_service_daemon 'pollmydevice'
}
