# GPIO initialization
echo 78 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio78/direction
echo 1 > /sys/class/gpio/gpio78/value
echo 91 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio91/direction
echo 0 > /sys/class/gpio/gpio91/value
echo 124 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio124/direction
echo 1 > /sys/class/gpio/gpio124/value
echo 80 > /sys/class/gpio/export
echo in > /sys/class/gpio/gpio80/direction
echo 88 > /sys/class/gpio/export
echo in > /sys/class/gpio/gpio88/direction
echo 83 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio83/direction
echo 1 > /sys/class/gpio/gpio83/value
echo 69 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio69/direction
echo 0 > /sys/class/gpio/gpio69/value
echo 77 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio77/direction
echo 1 > /sys/class/gpio/gpio77/value