#!/bin/sh
read -p "WARNING: you can loose Linux on your device. All your configs will be erased, save them. Make sure if you have an verified /tmp/sysupgrade_RTU968.tar !!! Don't turn off the device. Want to continue?(YES/n): " -n 3 -r
echo    # (optional) move to a new line
if [[ $REPLY == 'YES' ]]
then

	cd /tmp/
	if [ ! -f /tmp/sysupgrade_RTU968.tar ]; 
	then
    		echo "Sysupgrade file not found!"
	else
		tar -xvf sysupgrade_RTU968.tar
		mtd erase updroot
		mtd write rootfs.img  updroot
		mtd verify rootfs.img updroot
		fw_setenv filesize_rootfs $(printf %x $(stat -c %s rootfs.img))
		mtd erase kernel
		mtd write openwrt-mxs-uImage kernel
		mtd verify openwrt-mxs-uImage kernel
		fw_setenv filesize_kernel $(printf %x $(stat -c %s openwrt-mxs-uImage))
		mtd erase fdt
		mtd write fdt.dtb fdt
		mtd verify fdt.dtb fdt
		fw_setenv filesize_fdt $(printf %x $(stat -c %s fdt.dtb))
		fw_setenv update_flag 15963
		reboot
	fi

else
	printf "System Upgrade was cancelled. If you want to do it, plaese, print \"YES\" next time\n"

fi